@baseUrl={{$dotenv BASEURL}}


###############################################################################
# @name app_version
###############################################################################
GET {{baseUrl}}/app/version



###############################################################################
# @name app_webapiVersion
###############################################################################
GET {{baseUrl}}/app/webapiVersion



###############################################################################
# @name app_buildInfo
###############################################################################
GET {{baseUrl}}/app/buildInfo



###############################################################################
# @name app_shutdown
###############################################################################
GET {{baseUrl}}/app/shutdown



###############################################################################
# @name app_preferences
###############################################################################
GET {{baseUrl}}/app/preferences



###############################################################################
# @name app_setPreferences
###############################################################################
GET {{baseUrl}}/app/setPreferences
    ?json={"up_limit": 200}


###############################################################################
# @name app_defaultSavePath
###############################################################################
GET {{baseUrl}}/app/defaultSavePath



###############################################################################
#
###############################################################################