@baseUrl={{$dotenv BASEURL}}


###############################################################################
# @name torrents_info
###############################################################################
GET {{baseUrl}}/torrents/info
Content-Type: application/json



###############################################################################
# @name torrents_properties
###############################################################################
GET {{baseUrl}}/torrents/properties
    ?hash={{torrents_info.response.body.$.0.hash}}



###############################################################################
# @name torrents_trackers
###############################################################################
GET {{baseUrl}}/torrents/trackers
    ?hash={{torrents_info.response.body.$.0.hash}}



###############################################################################
# @name torrents_webseeds
###############################################################################
GET {{baseUrl}}/torrents/webseeds
    ?hash={{torrents_info.response.body.$.0.hash}}



###############################################################################
# @name torrents_files
###############################################################################
GET {{baseUrl}}/torrents/files
    ?hash={{torrents_info.response.body.$.0.hash}}



###############################################################################
# @name torrents_pieceStates
###############################################################################
GET {{baseUrl}}/torrents/pieceStates
    ?hash={{torrents_info.response.body.$.0.hash}}
