@baseUrl={{$dotenv BASEURL}}


###############################################################################
# @name transfer_info
###############################################################################
GET {{baseUrl}}/transfer/info



###############################################################################
# @name transfer_speedLimitsMode
###############################################################################
GET {{baseUrl}}/transfer/speedLimitsMode



###############################################################################
# @name transfer_toggleSpeedLimitsMode
###############################################################################
GET {{baseUrl}}/transfer/toggleSpeedLimitsMode



###############################################################################
# @name transfer_downloadLimit
###############################################################################
GET {{baseUrl}}/transfer/downloadLimit



###############################################################################
# @name transfer_setDownloadLimit
###############################################################################
GET {{baseUrl}}/transfer/setDownloadLimit
    ?limit=2097152



###############################################################################
# @name transfer_uploadLimit
###############################################################################
GET {{baseUrl}}/transfer/uploadLimit



###############################################################################
# @name transfer_setUploadLimit
###############################################################################
GET {{baseUrl}}/transfer/setUploadLimit
    ?limit=1024



###############################################################################
# @name transfer_banPeers
###############################################################################
GET {{baseUrl}}/transfer/banPeers
    ?peers=host:port

